src/Entity/UserTest.php
<?php

namespace App\Entity;

use App\Repository\UserTestRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserTestRepository::class)
 */
class UserTest implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }
}

src/Controller/SecurityController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\RegistrationType;
use Doctrine\Persistence\ObjectManager;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

class SecurityController extends AbstractController
{
    /**
     * @Route("/inscription", name="security_registration")
     */
    public function registration(Request $request, UserPasswordEncoderInterface $encoder){
        $manager = $this->getDoctrine()->getManager();
        $user = new User();

        $form = $this->createForm(RegistrationType::class, $user);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid())
        {
            $hash = $encoder->encodePassword($user, $user->getPassword());
            $user->setPassword($hash);
            $manager->persist($user);
            $manager->flush();
            return $this->redirectToRoute('security_login');
        }

        return $this->render('security/registration.html.twig', [
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/connexion", name="security_login");
     */
    public function login(){
        return $this->render('security/login.html.twig');
    }

    /**
     * @Route("deconnexion", name="security_logout");
     */
    public function logout(){}
}

templates/security/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello SecurityController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/Users/FORMATION/Documents/Formation/symfony/collection_jeux/src/Controller/SecurityController.php'|file_link(0) }}">src/Controller/SecurityController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/Users/FORMATION/Documents/Formation/symfony/collection_jeux/templates/security/index.html.twig'|file_link(0) }}">templates/security/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/security/login.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h1>Connexion</h1>

    <form action="{{ path('security_login') }}" method="post">
        <div class="form-group">
            <input placeholder="Adress email ..." required name="_username" type="text" class="form-control">
        </div>
        <div class="form-group">
            <input placeholder="Mot de passe ..." required name="_password" type="password" class="form-control">
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-success">Connexion !</button>
        </div>
    </form>

{% endblock %}

templates/security/registration.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h1>Inscription sur le site </h1>

    {{ form_start(form) }}

    {{ form_row(form.username, {'label': 'Nom d\'utilisateur', 'attr':
    {'placeholder': 'Nom d\'utilisateur ...'}}) }}
    {{ form_row(form.email, {'label': 'Adresse email', 'attr':
    {'placeholder': 'Adresse email ...'}}) }}
    {{ form_row(form.password, {'label': 'Mot de passe', 'attr':
    {'placeholder': 'Mot de passe ...'}}) }}
    {{ form_row(form.confirm_password, {'label': 'Confirmation de mot de passe', 'attr':
    {'placeholder': 'Répétez votre mot de passe ...'}}) }}

    <button type="submit" class="btn btn-success">Inscription !</button>

    {{ form_end(form) }}

{% endblock %}