src/Entity/UserGame.php
<?php

namespace App\Entity;

use App\Repository\UserGameRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=UserGameRepository::class)
 */
class UserGame
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $bought_at;

    /**
     * @ORM\ManyToMany(targetEntity=Platform::class, inversedBy="userGames")
     */
    private $platform;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="userGame")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\ManyToOne(targetEntity=Game::class, inversedBy="userGame")
     * @ORM\JoinColumn(nullable=false)
     */
    private $game;

    public function __construct()
    {
        $this->platform = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }


    public function getBoughtAt(): ?\DateTime
    {
        return $this->bought_at;
    }

    public function setBoughtAt(?\DateTime $bought_at): self
    {
        $this->bought_at = $bought_at;

        return $this;
    }

    /**
     * @return Collection|Platform[]
     */
    public function getPlatform(): Collection
    {
        return $this->platform;
    }

    public function addPlatform(Platform $platform): self
    {
        if (!$this->platform->contains($platform)) {
            $this->platform[] = $platform;
        }

        return $this;
    }

    public function removePlatform(Platform $platform): self
    {
        $this->platform->removeElement($platform);

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getGame(): ?Game
    {
        return $this->game;
    }

    public function setGame(?Game $game): self
    {
        $this->game = $game;

        return $this;
    }
}

src/Form/UserGameType.php
<?php

namespace App\Form;

use App\Entity\Game;
use App\Entity\Platform;
use App\Entity\UserGame;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UserGameType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('bought_at')
            ->add('platform', EntityType::class, [
                'class' => Platform::class,
                'choice_label' => 'name',
                'multiple' => true,
                'expanded' => true
            ])
            //->add('user')
            ->add('game', EntityType::class, [
                'class' => Game::class,
                'choice_label' => 'title',
                'multiple' => false,
                'expanded' => true
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => UserGame::class,
        ]);
    }
}

src/Controller/UserGameController.php
<?php

namespace App\Controller;

use App\Entity\UserGame;
use App\Form\UserGameType;
use App\Repository\UserGameRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/user/game")
 */
class UserGameController extends AbstractController
{
    /**
     * @Route("/", name="user_game_index", methods={"GET"})
     */
    public function index(UserGameRepository $userGameRepository): Response
    {
        return $this->render('user_game/index.html.twig', [
            'user_games' => $userGameRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="user_game_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $user = $this->getUser();
        $userGame = new UserGame();
        $form = $this->createForm(UserGameType::class, $userGame);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $userGame->setUser($user);
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($userGame);
            $entityManager->flush();

            return $this->redirectToRoute('user_game_index');
        }

        return $this->render('user_game/new.html.twig', [
            'user_game' => $userGame,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="user_game_show", methods={"GET"})
     */
    public function show(UserGame $userGame): Response
    {
        return $this->render('user_game/show.html.twig', [
            'user_game' => $userGame,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="user_game_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, UserGame $userGame): Response
    {
        $form = $this->createForm(UserGameType::class, $userGame);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('user_game_index');
        }

        return $this->render('user_game/edit.html.twig', [
            'user_game' => $userGame,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="user_game_delete", methods={"POST"})
     */
    public function delete(Request $request, UserGame $userGame): Response
    {
        if ($this->isCsrfTokenValid('delete'.$userGame->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($userGame);
            $entityManager->flush();
        }

        return $this->redirectToRoute('user_game_index');
    }
}

templates/user_game/_delete_form.html.twig
<form method="post" action="{{ path('user_game_delete', {'id': user_game.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user_game.id) }}">
    <button class="btn">Delete</button>
</form>

templates/user_game/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/user_game/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit UserGame{% endblock %}

{% block body %}
    <h1>Edit UserGame</h1>

    {{ include('user_game/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('user_game_index') }}">back to list</a>

    {{ include('user_game/_delete_form.html.twig') }}
{% endblock %}

templates/user_game/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}UserGame index{% endblock %}

{% block body %}
    <h1>UserGame index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Bought_at</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for user_game in user_games %}
            <tr>
                <td>{{ user_game.id }}</td>
                <td>{{ user_game.boughtAt ? user_game.boughtAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('user_game_show', {'id': user_game.id}) }}">show</a>
                    <a href="{{ path('user_game_edit', {'id': user_game.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('user_game_new') }}">Create new</a>
{% endblock %}

templates/user_game/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New UserGame{% endblock %}

{% block body %}
    <h1>Create new UserGame</h1>

    {{ include('user_game/_form.html.twig') }}

    <a href="{{ path('user_game_index') }}">back to list</a>
{% endblock %}

templates/user_game/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}UserGame{% endblock %}

{% block body %}
    <h1>UserGame</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ user_game.id }}</td>
            </tr>
            <tr>
                <th>Bought_at</th>
                <td>{{ user_game.boughtAt ? user_game.boughtAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('user_game_index') }}">back to list</a>

    <a href="{{ path('user_game_edit', {'id': user_game.id}) }}">edit</a>

    {{ include('user_game/_delete_form.html.twig') }}
{% endblock %}