src/Entity/Game.php
<?php

namespace App\Entity;

use App\Repository\GameRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=GameRepository::class)
 */
class Game
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min = 2, max = 255, minMessage="Le titre doit avoir au minimum 2 caractères et au maximum 255 caractères.")
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     * @Assert\Length(min = 5, minMessage="La description doit avoir au minimum 5 caractères.")
     */
    private $description;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $created_at;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $sales_number;

    /**
     * @ORM\Column(type="string", length=500, nullable=true)
     * @Assert\Url()
     */
    private $image;

    /**
     * @ORM\ManyToMany(targetEntity=Genre::class, inversedBy="games")
     */
    private $Genre;

    /**
     * @ORM\ManyToMany(targetEntity=Platform::class, inversedBy="games")
     */
    private $Plateform;

    /**
     * @ORM\OneToMany(targetEntity=UserGame::class, mappedBy="game", orphanRemoval=true)
     */
    private $userGame;

    public function __construct()
    {
        $this->Genre = new ArrayCollection();
        $this->Plateform = new ArrayCollection();
        $this->userGame = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getCreatedAt(): ?\DateTime
    {
        return $this->created_at;
    }

    public function setCreatedAt(?\DateTime $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getSalesNumber(): ?int
    {
        return $this->sales_number;
    }

    public function setSalesNumber(?int $sales_number): self
    {
        $this->sales_number = $sales_number;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    /**
     * @return Collection|Genre[]
     */
    public function getGenre(): Collection
    {
        return $this->Genre;
    }

    public function addGenre(Genre $genre): self
    {
        if (!$this->Genre->contains($genre)) {
            $this->Genre[] = $genre;
        }

        return $this;
    }

    public function removeGenre(Genre $genre): self
    {
        $this->Genre->removeElement($genre);

        return $this;
    }

    /**
     * @return Collection|Platform[]
     */
    public function getPlateform(): Collection
    {
        return $this->Plateform;
    }

    public function addPlateform(Platform $plateform): self
    {
        if (!$this->Plateform->contains($plateform)) {
            $this->Plateform[] = $plateform;
        }

        return $this;
    }

    public function removePlateform(Platform $plateform): self
    {
        $this->Plateform->removeElement($plateform);

        return $this;
    }

    /**
     * @return Collection|UserGame[]
     */
    public function getUserGame(): Collection
    {
        return $this->userGame;
    }

    public function addUserGame(UserGame $userGame): self
    {
        if (!$this->userGame->contains($userGame)) {
            $this->userGame[] = $userGame;
            $userGame->setGame($this);
        }

        return $this;
    }

    public function removeUserGame(UserGame $userGame): self
    {
        if ($this->userGame->removeElement($userGame)) {
            // set the owning side to null (unless already changed)
            if ($userGame->getGame() === $this) {
                $userGame->setGame(null);
            }
        }

        return $this;
    }
}

src/Form/GameType.php
<?php

namespace App\Form;

use App\Entity\Game;
use App\Entity\Genre;
use App\Entity\Platform;
use Symfony\Component\Form\AbstractType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class GameType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title', TextType::class, [
                "attr" => [
                    "class" => "form-control"
                ]
            ])
            ->add('description', TextareaType::class, [
                "attr" => [
                    "class" => "form-control"
                ]
            ])
            //->add('created_at')
            ->add('sales_number')
            ->add('image')
            ->add('Genre', EntityType::class, [
                'class' => Genre::class,
                'choice_label' => 'title',
                'multiple' => true,
                'expanded' => true
            ])
            ->add('Plateform', EntityType::class, [
                'class' => Platform::class,
                'choice_label' => 'name',
                'multiple' => true,
                'expanded' => true
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Game::class,
        ]);
    }
}

src/Controller/GameController.php
<?php

namespace App\Controller;

use App\Entity\Game;
use App\Entity\User;
use App\Form\GameType;
use App\Repository\GameRepository;
use App\Repository\UserRepository;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class GameController extends AbstractController
{
    /**
     * @Route("/game", name="game")
     */
    public function game(Request $request, GameRepository $repo, PaginatorInterface $paginator): Response
    {
        
        $games = $repo->findAll();

        $games = $paginator->paginate(
            $games, /* query NOT result */
            $request->query->getInt('page', 1)/*page number*/,
            6/*limit per page*/
        );

        return $this->render('default/index.html.twig', [
            'controller_name' => 'DefaultController',
            'games' => $games
        ]);
    }

    /**
     * @Route("/game/new", name="game_new")
     * @Route("/game/edit/{id}", name="game_edit")
     */
    public function form(Game $game = null, Request $request): Response
    {
        $user = $this->getUser();
        //Gestion de la création et de la mise à jour des jeux
        if(!$game){                 //si c'est la création du jeu
            $game = new Game();
        }
        
        $form = $this->createForm(GameType::class, $game);
        $form->handleRequest($request);
        
        if($form->isSubmitted() && $form->isValid())
        {
            if(!$game->getId()){
                $game->setCreatedAt(new \DateTime());
            }
            $em = $this->getDoctrine()->getManager();

            $em->persist($game);
            $em->flush();

            return $this->redirectToRoute('game_show', ['id' => $game->getId()]);
        }

        return $this->render('game/new.html.twig', [
            "form" => $form->createView(),
            "editMode" => $game->getId() !== null
        ]);
    }

    /**
     * @Route("/", name="home")
     */
    public function home(){
        return $this->render('game/home.html.twig');
    }

    /**
     * @Route("/game/{id}", name="game_show")
     */
    public function show(Game $game){
        
        
        return $this->render('game/show.html.twig', [
            'game' => $game
        ]);
    }

    /**
     * @Route("/game/delete/{id}", name="game_delete")
     */
    public function delGame(GameRepository $gameRepository, $id)
    {
        $game = $gameRepository->findOneById($id);

        if (!is_null($game)) {
            $em=$this->getDoctrine()->getManager();
            $em->remove($game);
            $em->flush();

            $this->addFlash(
                'notice',
                'Your changes were saved!'
            );
        }

        return $this->redirectToRoute('game');
    }
    
}

templates/game/home.html.twig
{% extends 'base.html.twig' %}
{% block body %}

<h1>Bienvenue dans votre collection des jeux</h1>

{% endblock %}

templates/game/new.html.twig
{% extends "base.html.twig" %}


{% block title %}
    {% if editMode %}
        Modifier un jeu
    {% else %}
        Ajouter un jeu 
    {% endif %}     
    
 {% endblock %}

{% block body %}
    <br>
    <h1>
        {% if editMode %}
            Modifier un jeu
        {% else %}
            Ajouter un jeu 
        {% endif %}    
    </h1>
    <hr>
    {{ form_start(form) }}

    <div class="form-group">
        <label>Nom du jeu</label>
        {{ form_widget(form.title, {'attr': {'placeholder': 'Nom du jeu'}}) }}
    </div>
    <div class="form-group">
        {{ form_label(form.description) }}
        {{ form_widget(form.description) }}
    </div>
    <div class="form-group">
        <label>Nombre de ventes</label>
        {{ form_widget(form.sales_number) }}
    </div>
    <div class="form-group">
        {{ form_label(form.image) }}
        {{ form_widget(form.image, {'attr': {'placeholder': 'URL de l\'image'}}) }}
    </div>
    <div class="cat-platf">
        <div class="form-group">
            <label>Catégorie</label>
            {{ form_widget(form.Genre) }}
        </div>
        <div class="form-group">
            {{ form_label(form.Plateform) }}
            {{ form_widget(form.Plateform) }}
        </div>
    </div>
    <br>
    <button class="btn btn-primary">
    {% if editMode %}
        Mettre à jour
    {% else %}
        Ajouter le jeu
    {% endif %}
    </button>

    {{ form_end(form) }}
    <br>
{% endblock %}

templates/game/show.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    {# {% include 'block/gameblock.html.twig' with {'game': game} %} #}
    <div class="container">
            <div class="row">
                
                <div class="col-lg-9">
                    <br>
                    <h3 class="card-title">{{game.title}}</h3>
                    <div class="card mt-4">
                        <img class="card-img-top img-fluid" src="{{game.image}}" alt="Image du jeu" />
                        <div class="card-body">
                            
                            <div class="metadata">Enregistré le {{game.createdAt | date
                                ('d/m/Y')}} à {{game.createdAt | date('H:i')}}
                                
                            </div>
                            <hr>
                            <h5>Description:</h5>
                            {# affichage de description limite a 25 characters #}
                            <p class="card-text">{{ game.description }}</p> 

                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            <div>
                <br>
                <h4 class="card-title">Ce jeu est dans les catégorie: </h4>
                    <span class="catplat-info">
                        {% for g in game.Genre %}  
                            {{g.title}} |
                        {% endfor %}  
                    <span><hr>   
            </div>
            <div>
                <h4 class="card-title">Ce jeu tourne sur les plateformes suivantes: </h4>
                    <span class="catplat-info">
                        {% for p in game.Plateform %}  
                            {{p.name}} |
                        {% endfor %}  
                    <span>    
            </div>
        </div><br>
        <a href="{{ path('game_edit', {'id': game.id}) }}" class="btn btn-primary" id="b"> Modifier </a>
        <a onclick="return confirm('Le jeu a été effacé')" href="{{ path('game_delete', {'id': game.id}) }}" class="btn btn-primary" id="b"> Supprimer </a>
{% endblock %}